// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "rulesInit": boolean;
      "ruleWarningDisabled": boolean;
      "deleteMessageDisabled": boolean;
      "menuSortBy": string;
      "showPopup": boolean;
      "rulesSortColumnIndex": number;
      "rulesSortColumnAscending": boolean;
      "inciteful.enabled": boolean;
      "reading.enabled": boolean;
      "import.enabled": boolean;
      "docxCited.enabled": boolean;
      "connectionMapEnableHighlightLayer": boolean;
      "connectionMapTimelineJson": string;
      "openLibraryDbPath": string;
      "kitaplarDbPath": string;
      "kutuphaneSemanticUrl": string;
      "citation.layers.crossref": boolean;
      "citation.layers.openalex": boolean;
      "citation.layers.openCitations": boolean;
      "openalex.mailto": string;
      "openalex.cacheDays": number;
      "anki.enabled": boolean;
      "anki.host": string;
      "anki.port": number;
      "anki.key": string;
      "anki.deckName": string;
      "anki.modelName": string;
      "note.markdb.enabled": boolean;
      "note.markdb.vaultPath": string;
      "note.markdb.matchStrategy": string;
      "note.markdb.tag": string;
      "semantic.kutuphane.enabled": boolean;
      "semantic.kutuphaneUrl": string;
      "semantic.kutuphane.graph.enabled": boolean;
      "semantic.zotseek.enabled": boolean;
      "note.workspace.enabled": boolean;
      "citegeist.enabled": boolean;
      "refchecker.enabled": boolean;
      "refchecker.url": string;
      "kutuphane.aiUrl": string;
      "vendoredZotSeek": boolean;
      "embeddingModel": string;
    };
  }
}
